export default {
    buttonSelector: '[class="mh-catalog-btn"]',
    list: '.mm__list',
    portalCategoryList: '.portal-category__list',
    portalCategoryItem:'li[class="portal-category__item"] a[class="portal-category__item-link"]',
    formInputFirst:'.f-range__values .f-range__form-input:first',
    formInputLast:'.f-range__values .f-range__form-input:last',
    categoryId:'.accordion:has([data-id="${categoryId}"])',
    searchInput:'.v-search-input input',
    productCard:'div[class="product-card"]',
    productCardTitle:'.product-card__title',
    btnCart:'.v-btn--cart',
    checkoutModal:'.checkout_modal',
    comebacK:'[class="comeback"]',
    priceBox:'div[class="price-box__cur"]',
    totalBoxPrice: '.total-box__price',
    closeRemove: '.vi__close.remove',
    closeBtn:'.v-modal__close-btn',
    cartPopupEmpty : '.cart-popup_empty',
    searchFormInput : '#search-form__input',
    searchFormSubmitButton : '.search-form__submit-button',
    modalSubmitButton : '.a-button--block a-button--lg',
    input__container : '.a-input__container',
    authWithPassButton: '.auth__enter-password > button',
    authLogin: '[name="phoneEmail"]',
    authPassword :'[name="password"]',
    loginButton: '.auth__form button[type="submit"]',
    profile :'.mh-profile',
    btnMessage:'span.f-popup__btn-message',
    sum:'.v-pb__cur .sum',
    spinner:'div.loading-block-gif',
};
